name: netmedia
favicon: null
layout_spectrum: 0.5817229298409075
typography_spectrum: 0.4394517519976944
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.224776265444234
  lightness: 0.5790976823773235
  saturation: 0.9878962102811784
  rhythmicContrast: 0.7172247625421733
purpose: []
